-- Create ACCOUNTS table
CREATE TABLE accounts (
    account_id VARCHAR2(20) PRIMARY KEY,
    balance NUMBER(15,2) NOT NULL
);

-- Create TRANSACTIONS table
CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMBER(10,2) NOT NULL,
    currency VARCHAR2(10) NOT NULL,
    status VARCHAR2(20),
    transaction_date DATE DEFAULT SYSDATE
);

-- Insert sample accounts
INSERT INTO accounts (account_id, balance) VALUES ('123456', 5000);
INSERT INTO accounts (account_id, balance) VALUES ('654321', 10000);
COMMIT;
